### Testing Dupes
Wanted to see if old entries had duplicated entries for starttime/bike_id

In [1]:
import pandas as pd

df = pd.read_csv(
    "/Users/patrickcleary/Downloads/2013-citibike-tripdata/201306-citibike-tripdata.csv"
)

In [5]:
df[df.duplicated(subset=['starttime', 'bikeid'], keep=False)]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2925,1087,2013-06-01 13:29:52,2013-06-01 13:47:59,514,12 Ave & W 40 St,40.760875,-74.002777,470.0,W 20 St & 8 Ave,40.743453,-74.000040,19130,Subscriber,1983.0,2
2927,1112,2013-06-01 13:29:52,2013-06-01 13:48:24,514,12 Ave & W 40 St,40.760875,-74.002777,470.0,W 20 St & 8 Ave,40.743453,-74.000040,19130,Subscriber,1983.0,2
42486,412,2013-06-04 18:02:47,2013-06-04 18:09:39,509,9 Ave & W 22 St,40.745497,-74.001971,446.0,W 24 St & 7 Ave,40.744876,-73.995299,18454,Subscriber,1954.0,1
42487,430,2013-06-04 18:02:47,2013-06-04 18:09:57,509,9 Ave & W 22 St,40.745497,-74.001971,446.0,W 24 St & 7 Ave,40.744876,-73.995299,18454,Subscriber,1954.0,1
44163,923,2013-06-04 18:56:58,2013-06-04 19:12:21,484,W 44 St & 5 Ave,40.755003,-73.980144,305.0,E 58 St & 3 Ave,40.760958,-73.967245,16825,Subscriber,1985.0,1
44164,48179,2013-06-04 18:56:58,2013-06-05 08:19:57,484,W 44 St & 5 Ave,40.755003,-73.980144,512.0,W 29 St & 9 Ave,40.750073,-73.998393,16825,Subscriber,1985.0,1
50063,1122,2013-06-05 08:53:11,2013-06-05 09:11:53,468,Broadway & W 56 St,40.765265,-73.981923,444.0,Broadway & W 24 St,40.742354,-73.989151,20350,Subscriber,1973.0,1
50064,34752,2013-06-05 08:53:11,2013-06-05 18:32:23,468,Broadway & W 56 St,40.765265,-73.981923,280.0,E 10 St & 5 Ave,40.733320,-73.995101,20350,Subscriber,1973.0,1
126930,1223,2013-06-11 17:01:51,2013-06-11 17:22:14,442,W 27 St & 7 Ave,40.746647,-73.993915,461.0,E 20 St & 2 Ave,40.735877,-73.982050,17258,Subscriber,1981.0,1
126933,1216,2013-06-11 17:01:51,2013-06-11 17:22:07,442,W 27 St & 7 Ave,40.746647,-73.993915,461.0,E 20 St & 2 Ave,40.735877,-73.982050,17258,Subscriber,1981.0,1
290956,1732,2013-06-20 16:32:27,2013-06-20 17:01:19,290,2 Ave & E 58 St,40.760203,-73.964785,410.0,Suffolk St & Stanton St,40.720664,-73.985180,17659,Subscriber,1985.0,2
290957,1724,2013-06-20 16:32:27,2013-06-20 17:01:11,290,2 Ave & E 58 St,40.760203,-73.964785,410.0,Suffolk St & Stanton St,40.720664,-73.985180,17659,Subscriber,1985.0,2